export const names = [
  'Porsche 911',
  'Chevrolet Corvette',
  'Ford Mustang',
  'BMW M3',
  'Audi R8',
  'Nissan GT-R',
  'Lamborghini Aventador',
  'Ferrari 488 GTB',
  'McLaren 720S',
  'Aston Martin Vantage',
  'Jaguar F-Type',
  'Mercedes-AMG GT',
  'Dodge Viper',
  'Lexus LC',
  'Toyota Supra',
  'Acura NSX',
  'Subaru WRX STI',
  'Lotus Evora',
  'Alfa Romeo 4C',
  'Chevrolet Camaro ZL1',
];

export const colors = [
  'red',
  'violet',
  'dodgerblue',
  'yellow',
  'magenta',
  'cyan',
  'coral',
  'gold',
  'aqua',
  'orangered',
  'royalblue',
  'fuchsia',
  'orchid',
  'springgreen',
  'orange',
  'pink',
  'white',
  'lime',
  'crimson',
  'deeppink',
];
